### ISSUE TITLE
Feature: Командные WIP-лимиты

### ISSUE THREAD

**Issue by Anastasiia771** [TinkoffCreditSystems/jira-helper#100]
Есть потребность в доработке jira-helper в части командных wip-лимитов:

- есть более верхние уровни (эпики, проекты), где ведутся работы всех команд одного направления;
история такая же как на уровне одной команды - нужно сократить кол-во одновременно выполняемой работы, но в разрезе команд (как индивидуальные wip-лимиты, только на команду). Например, 3 эпика в работе на зеленую команду, 4 эпика на красную и т.д.

- история масштабируема; такие лимиты полезны на направлениях на уровне программы

- можно переиспользовать функционал индивидуальных wip-лимитов; вместо assignee выводить Первые буквы команды или что-то такое (edited) (во вложении пример)

![image (4)](https://user-images.githubusercontent.com/79245442/108316264-be4ec600-71cd-11eb-95ac-e9c853dd8477.png)

**Comment by britishpop** [comment]
Используем для описанной цели личные WIP-лимиты. Просто ассайним тикеты на тимлидов и ограничиваем максимальное количество ассайнов на каждого тимлида

**Comment by pavelpower** [comment]
Ладно, надо признать, что если использовать WIP-лимит по какому-то полю, то тонкость настройки сильно повысится.

**Comment by Anastasiia771** [comment]
ставить лимиты на тимлидов тоже думали, как костыльное решение, пока нет возможности поставить лимит на команду

итого: подскажите, пожалуйста, возьмут в работу эту задачу? и если да, то когда по срокам возможна реализация?
