### ISSUE TITLE
Can't make swimlane expedite [BUG]

### ISSUE THREAD

**Issue by britishpop** [TinkoffCreditSystems/jira-helper#103]
**Describe the bug**
Не выставляется экспедайт в слимитах свимлейна. Свимлейн нельзя вывести из под колоночных лимитов

**To Reproduce**
1. Зайти в настройки доски
2. Зайти в настройку свимлейнов
3. Нажать "Edit swimlane limits"
4. Сделать любой свимлейн Expedite
5. Нажать Save
6. В консоль падает ошибка, свойство expedite не сохраняется

**Expected behavior**
Ошибок не происходит, свимлейн становится экспедайт и не учитывается в лимитах колонок

**Screenshots**
![Screenshot 2021-02-24 at 13 41 54](https://user-images.githubusercontent.com/37972827/108988928-142bde00-76a6-11eb-8c88-cededc11d2e5.png)

**Desktop (please complete the following information):**
 - JIRA Server Data Center 8.13.3

**Comment by davakh** [comment]
Ошибка запроса пока будет появляться, т.к. jira отправляет `Content-Type: application/json` и пустое тело. Подумаем ещё, как решить, но функционал пока исправен
