### ISSUE TITLE
Feature: WIP лимиты на колонки в Swimlane

### ISSUE THREAD

**Issue by ArthurIshmukhametov** [TinkoffCreditSystems/jira-helper#111]
**Проблема**
В нашем проекте разные части команды на одной борде ведут независящие друг от друга задачи (разработка и автотесты) в разных свимлейнах. Для нас важны лимиты на колонки, но, к примеру, настроить отдельно лимит на todo для разработчиков и тестировщиков нельзя.

**Решение**
При установке лимитов на колонки добавить возможность устанавливать свимлейн, в котором будет действовать лимит

**Обходное решение**
Добавил лимит на свимлейн целиком. Теперь колонки не заблочены, но количество задач в каждом статусе и в каждом свимлейне приходится считать самому.

**Comment by pavelpower** [comment]
Предполагаю, что вашу проблему может решить то, что сделали в версии 2.11.0
реализованую в задаче https://github.com/TinkoffCreditSystems/jira-helper/issues/100

Это будет выглядеть немного иначе, но сочетание Field WIP-лимитов, и WIP-лимитов на колонки может решить ваш кейс
