### ISSUE TITLE
[BUG] Не работает лимитирование по кастомным полям

### ISSUE THREAD

**Issue by britishpop** [TinkoffCreditSystems/jira-helper#113]
**Describe the bug**
WIP лимит по кастомному полю тикета не работает. Просто не видит на доске тикеты, которые подходят ему по заданному условию

**To Reproduce**
1. Создать лимит по кастомному полю
2. Зайти на доску, где он должен работать
3. Увидеть, что лимит пустой, как будто по его условию нет ни одного тикета

**Expected behavior**
Лимит видит тикеты, которы подходят под его условие

**Screenshots**
Ошибка при создании лимита по кастомному полю (может быть релевантно)
![image](https://user-images.githubusercontent.com/37972827/112997361-b9d6df00-9175-11eb-9051-1a5b5993b73b.png)

Лимит на Billings показывает 0/2, хотя должен показать 2/2
![image](https://user-images.githubusercontent.com/37972827/112997467-d115cc80-9175-11eb-9baf-f12dc9075f33.png)

**Desktop (please complete the following information):**
 - JIRA data center 8.13.3

**Additional context**
Даже моя мама использует jira-helper

**Comment by pavelpower** [comment]
Если не использовать свимлайны

**Comment by pavelpower** [comment]
Починили багу тут https://github.com/TinkoffCreditSystems/jira-helper/pull/115
Выйдет на google store версия 2.11.1 проверь
