### ISSUE TITLE
Вывод времени нахождения карточки в статусе не используя "Field Name"

### ISSUE THREAD

**Issue by Hitotose** [TinkoffCreditSystems/jira-helper#118]
Возможность вывода на карточку времени её нахождения в статусе не расходуя поля в "Card layout" – "Field Name".

**Comment by pavelpower** [comment]
Это и так есть в нативной JIRA!
<img width="488" alt="Screenshot 2021-05-14 at 00 17 04" src="https://user-images.githubusercontent.com/301646/118188928-cd9a8400-b449-11eb-90ae-5a5df9701e2b.png">
