### ISSUE TITLE
[BUG] Не отображаются групповые лимиты на доске

### ISSUE THREAD

**Issue by Anastasiia771** [TinkoffCreditSystems/jira-helper#126]
На доске не отображаются групповые лимиты - см вложение 
![image](https://user-images.githubusercontent.com/79245442/118152532-7bdc0480-b41d-11eb-8c54-225898fe1e4b.png)

**Comment by pavelpower** [comment]
Вероятно, что после выставления WIP-лимитов, какую-то колонку пересоздали
И надо пересоздать WIP-лимиты на самом деле
<img width="904" alt="Screenshot 2021-05-13 at 22 51 38" src="https://user-images.githubusercontent.com/301646/118179320-cff6e100-b43d-11eb-8f09-61d15b7969cb.png">

**Comment by pavelpower** [comment]
И кстати, получается нельзя удалить в такому случае этот WIP-лимит из общего набора
