### ISSUE TITLE
Сохранять на JIRA-сервер template для задач

### ISSUE THREAD

**Issue by pavelpower** [TinkoffCreditSystems/jira-helper#13]
### При создании или редактировании задачи.

В поле Description можем создавать шаблон для задач.

Что нужно:
Нужно чтобы для выбранного проекта и выбранного типа задачи template сохронялся в properties на JIRA-сервер.

Чтобы все участники проекта могли использовать этот template для оформления задачи.

Как сейчас:
template сохроняется в Local Storage

<img width="647" alt="Снимок экрана 2020-03-21 в 13 01 23" src="https://user-images.githubusercontent.com/301646/77224185-1fac8600-6b74-11ea-90ec-8a94792f7e51.png">

**Comment by RustaLenin** [comment]
Jira Addon "Issue Templates" использует для шаблонов задачи в создаваемом аддоном проекте Templates
Можно пойти по аналогичному пути, при этом, коллеги получат возможность редактировать шаблоны - через саму Jira
Получить все шаблоны можно будет получить через API
Добавить новый шаблон можно будет по API
Ну и так далее...

Короче, вполне рабочий план.
Одно но, нафига так заморачиваться, если есть готовый плагин?

**Comment by pavelpower** [comment]
На JIRA сервер можно сохранять данные привязываясь к какому-то объекту.
Мы это делаем например к доске (для настроек доски)
А если мы создаем задачу из popup но нена доске, то не понятно за что привязатся.

В общем тут надо поразмыслить.
