### ISSUE TITLE
[BUG] Полностью перестал работать плагин в Jira Cloud

### ISSUE THREAD

**Issue by AndreyMoiseev** [TinkoffCreditSystems/jira-helper#148]
**Describe the bug**
Сегодня утром в Jira Cloud полностью перестал работать плагин Jira Helper. Не видно настроенных лимитов на доске, не видно дополнительных опций в настройках доски. При включенном плагине все выглядит так, как-будто плагин отключен или не установлен.
Также не работает плагин Jira Flow Companion, вероятно причины как-то связаны.

**Desktop (please complete the following information):**
 - JIRA Cloud

Возможно, в Jira Cloud выкатили новую версию или у нас в настройках Jira что-то поменяли. Подскажите как это траблшутить, куда смотреть.

**Comment by pavelpower** [comment]
<img width="1217" alt="Screenshot 2021-08-30 at 12 29 21" src="https://user-images.githubusercontent.com/301646/131318369-8bb6793f-37e2-4925-82a5-7b2abd9063cd.png">
<img width="1217" alt="Screenshot 2021-08-30 at 12 29 21" src="https://user-images.githubusercontent.com/301646/131318383-1acf47a2-b19b-4ee8-abdc-0709c6410000.png">
<img width="1379" alt="Screenshot 2021-08-30 at 12 29 05" src="https://user-images.githubusercontent.com/301646/131318387-be820ba9-df6f-438a-bed1-327d764f9f8d.png">


У меня все работает!
У вас случаем не было чистки БД?

С какого браузера вы работаете?

**Comment by AndreyMoiseev** [comment]
Браузер Chrome. Вижу, что у нас стал другой формат пути к доске: https://my-company.atlassian.net/jira/software/c/projects/MP/boards/138
Не знаю, от чего это зависит, попробую узнать у наших админов.

**Comment by pavelpower** [comment]
Dmitry Sokolov, [30 Aug 2021, 14:40:04]:
в джире поменялся урл к доске, может это связано как-то?
было https://companyname.atlassian.net/secure/RapidBoard.jspa?projectKey=PN&rapidView=12
стало https://companyname.atlassian.net/jira/software/c/projects/PN/boards/12
