### ISSUE TITLE
Добавить возможность заблюрить "чувствительные данные в JIRA"

### ISSUE THREAD

**Issue by pavelpower** [TinkoffCreditSystems/jira-helper#19]
Зачем это надо?

При обемне опытом настройки или использовании функционала в JIRA
Очень часто хочется показать свою рабочую JIRA.
Но при этом, чтобы не нарушать NDA по данным, хотелось бы их скрыть.

Чтобы это было возможно сделать нужно для версий JIRA 7, 8, Cloud найти css классы заголовков и текстов которые считаются Sensitive.

И по нажатию кнопки, необходимо перед загрузкой body с JIRA вставлять css
с размытием

Пример:
```
.class-name {
 text: transparent;
 text-shadow: #000 -1px 1px 10px;
}

.class-link {
 text: transparent;
 text-shadow: blue -1px 1px 10px;
}
```

**Comment by pavelpower** [comment]
:+1:

**Comment by stepev** [comment]
👍

**Comment by Shal1928** [comment]
+1

**Comment by Sergey-Titkov** [comment]
👍
