### ISSUE TITLE
[bug-template] Отсутствует возможность вставки шаблона задачи

### ISSUE THREAD

**Issue by rusichmr86** [TinkoffCreditSystems/jira-helper#21]
*Кейс:*
1. Открыть произвольную задачу, где предусмотрено создание подзадачи / acceptance bug
2. Нажать на "Создать подзадачу"

*Фактический результат:*
- Отсутствуют иконки для быстрого ввода шаблона
![Снимок экрана 2020-03-26 в 23 36 00](https://user-images.githubusercontent.com/36576314/77694125-986b7200-6fba-11ea-909a-87dce6bcbef5.png)

*Ожидаемый результат:*
- Кнопки создания / перезаписи шаблона есть
![Снимок экрана 2020-03-26 в 23 38 00](https://user-images.githubusercontent.com/36576314/77694351-ebddc000-6fba-11ea-9807-3d4115185f54.png)

**Comment by pavelpower** [comment]
Связано с https://github.com/TinkoffCreditSystems/jira-helper/issues/13
