### ISSUE TITLE
[Tetris-planing] При создании/удалении столбцов, пропадают кнопки "Merge columns into a group" и "Remove groups for the board"

### ISSUE THREAD

**Issue by rusichmr86** [TinkoffCreditSystems/jira-helper#23]
*Кейс:*
1. Перейти в настройки kanban доски, на которой есть задачи
2. В пункте настройки выбрать "Столбцы"
3. Создать либо удалить столбец

***Фактический результат:***
- Отсутствуют кнопки "Merge columns into a group" и "Remove groups for the board"

![screencast 2020-03-27 00-34-16](https://user-images.githubusercontent.com/36576314/77699112-d7052a80-6fc2-11ea-9395-6b54a4f87c81.gif)

***Ожидаемый результат:***
- Кнопки есть

**Comment by pavelpower** [comment]
Duplicate of #14
