### ISSUE TITLE
(?) [Tetris-planing] Отображаются поля min/max для не админа доски

### ISSUE THREAD

**Issue by rusichmr86** [TinkoffCreditSystems/jira-helper#24]
*Кейс:*
1. Перейти в настройки kanban доски, на которой есть задачи и пользователь не должен являться админом
2. В пункте настройки выбрать "Столбцы"

***Фактический результат:***
- Отображаются поля для ввода Минимального и максимального значения для столбца, хоть ввод и не возможен
![Снимок экрана 2020-03-27 в 0 53 27](https://user-images.githubusercontent.com/36576314/77700516-6ad7f600-6fc5-11ea-87cb-9d8ab50db67e.png)

**Comment by pavelpower** [comment]
А это чисто JIRA-так делает
