### ISSUE TITLE
Мелочи по оформлению репозитория

### ISSUE THREAD

**Issue by MarsiBarsi** [TinkoffCreditSystems/jira-helper#27]
Привет!

@pavelpower просил посмотреть репозиторий по опенсорсному оформлению 👀 

1. Было бы круто перевести README на английский. Можно оставить в двух вариациях, например: сначала на английском, после описание на русском

2. У вас проект лицензирован 2018-ым годом, а выложен в 2020. Мелочь, но можно циферку поменять и все права будут 100% под защитой :)

3. Совсем нет CHANGELOG'а или описаний, что поменялось в версиях. Версия 2.0, но чем она отлична от 1.0 непонятно

4. Можно добавить файл по контрибьютингу ([пример](https://github.com/TinkoffCreditSystems/ng-polymorpheus/blob/master/CONTRIBUTING.md)) и файл CODE_OF_CONDUCT ([пример](https://github.com/TinkoffCreditSystems/ng-polymorpheus/blob/master/CODE_OF_CONDUCT.md)) на случай, если кто-нибудь новый захочет законтрибьютить

5. Сейчас issue и описания к PR пишутся, как получится — можно сделать шаблоны и сложить их в папку .github ([пример](https://github.com/TinkoffCreditSystems/ng-polymorpheus/tree/master/.github))

6. Сейчас ревьюеры добавляются руками. Можно зафиксировать, за какой код отвечает какой гитхаб юзер в файле CODEOWNERS. Либо простой вариант — сделать дефолтных ревьюеров ([пример](https://github.com/TinkoffCreditSystems/ng-polymorpheus/blob/master/.github/CODEOWNERS)). Будут добавляться к PR автоматически и пинговаться на почту / в уведомления

7. Как я понял, у вас нет никакого CI? Можно сделать хотя бы простейшую сборку на Github Actions или Travis'е, может спасти от неожиданных проблем

**Comment by pavelpower** [comment]
- [ ] Было бы круто перевести README на английский. Можно оставить в двух вариациях, например: сначала на английском, после описание на русском

- [ ] У вас проект лицензирован 2018-ым годом, а выложен в 2020. Мелочь, но можно циферку поменять и все права будут 100% под защитой :)

- [ ] Совсем нет CHANGELOG'а или описаний, что поменялось в версиях. Версия 2.0, но чем она отлична от 1.0 непонятно

- [ ] Можно добавить файл по контрибьютингу (пример) и файл CODE_OF_CONDUCT (пример) на случай, если кто-нибудь новый захочет законтрибьютить

- [ ] Сейчас issue и описания к PR пишутся, как получится — можно сделать шаблоны и сложить их в папку .github (пример)

- [ ] Сейчас ревьюеры добавляются руками. Можно зафиксировать, за какой код отвечает какой гитхаб юзер в файле CODEOWNERS. Либо простой вариант — сделать дефолтных ревьюеров (пример). Будут добавляться к PR автоматически и пинговаться на почту / в уведомления

- [ ] Как я понял, у вас нет никакого CI? Можно сделать хотя бы простейшую сборку на Github Actions или Travis'е, может спасти от неожиданных проблем

**Comment by pavelpower** [comment]
Готово
