### ISSUE TITLE
Учитывать сабтаски в WIP-лимитах

### ISSUE THREAD

**Issue by SBabanova** [TinkoffCreditSystems/jira-helper#31]
В Jira есть возможность выбрать что считать в wip-лимитах
Добавить в jira-helper возможность выбирать, что учитывать в лимитах: все задачи или задачи без сабтасок
![image](https://user-images.githubusercontent.com/38456432/81664170-ec85c500-9447-11ea-8a91-9bf746c6b1af.png)

**Comment by pavelpower** [comment]
Sample request for getting info about the board:
```
AJS.$.get('/rest/greenhopper/1.0/xboard/work/allData.json?rapidViewId=1&selectedProjectKey=PFI')
.then(d=> console.log(d));
```

you can find field statistic in the response data:
```
{
....
statistics: {
    fieldConfigured: true,
    typeId: "issueCountExclSubs",
    id: "",
    name: "Issue Count,
    excluding sub-tasks"
}
... }
```

**Comment by pavelpower** [comment]
you can use rest api: 
```
AJS.$.get('/rest/agile/1.0/board/1/configuration').then(d=> console.log(d))
```
when `1`  rapidView id

and the response data 
```
columnConfig: {
....
constraintType: "issueCountExclSubs"
}
```
constraintType - may be `undefined`, may be `issueCount` and `issueCountExclSubs`
