### ISSUE TITLE
После снятия мержа колонок и повторного установления, нельзя установить вип лимит.

### ISSUE THREAD

**Issue by ignatenkonatalia** [TinkoffCreditSystems/jira-helper#34]
После снятия мержа колонок и повторного установления:
1. нельзя установить вип лимит на вторую и последующую группы колонок
2. в режиме настройки не отображается мерж второй и последующих групп колонок, хотя на панели они все же есть.
![2020-05-18 09 17 11](https://user-images.githubusercontent.com/65495438/82180046-630f4080-98e8-11ea-85a2-871ff029c51e.jpg)

**Comment by davakh** [comment]
Не получилось воспроизвести, есть возможность описать конкретно порядок действий?
