### ISSUE TITLE
Добавить возможность ограничивать WIP методом ограничения аватаром

### ISSUE THREAD

**Issue by pavelpower** [TinkoffCreditSystems/jira-helper#36]
В настройках ограничения указать сколько задач можно брать кому.
На верхней панели показывается количество использованых аватаров на задачу

Если аватары заканчиваются, все задачи с человеком начинают подсвечиваться красным бэкграундом.

<img width="1266" alt="Снимок экрана 2020-05-29 в 15 50 35" src="https://user-images.githubusercontent.com/301646/83261632-53370c80-a1c4-11ea-893c-54ae5715f9a4.png">

Для администратора доски необходима возможность настроить ограничения на человека отдельно от колонок и свимлайнов (по аватарам) иначе говоря - подсвечивать количество задач взятых человеком. И сигнализировать о нарушении установленного лимита.

Для этого можно использовать верхнюю панель над Qiuck-Filtrers
А насткройки ограничений производить в всплывающем окошке (как в тетрис-планировании)

Где можно выбрать человека и установить для него WIP-лимит
Нужна возможность установки WIP-лимита не только по общему количеству Assign на человека
Но и указывать в каких колонках необходимо производить этот подсчет
Так же нужно указать и возможность указать в каких свимлайнах производить подсчет по огранчиению на человека.

**Comment by Artbk** [comment]
Было бы классно, чтобы такое появилось не только с настраиваемом лимитом. Еще, чтобы контролировать загрузку сотрудника на канбане, было бы удобно отображать количество задач каждого типа у сотрудника, а так-же сумму стори поинтов. 
Если при этом можно информацию по загрузке показывать только по карточкам без флага(не заблокированным), то это еще лучше менеджеру будет показывать реальную загрузку по задачам.
С точки зрения реализации можно еще продумать , идея сырая. Главное видеть информацию, чтобы эффективно распределять задачи и не перегружать сотрудника или видеть, что простаивает.

**Comment by pavelpower** [comment]
> Будет классно, чтобы фича появилась не только с настраиваемым лимитом. Чтобы контролировать загрузку сотрудника на канбане, было бы удобно отображать количество задач сотрудника с разбивкой на типы задач, а так-же сумму SP.

@Artbk Это сразу несколько функций в одном
