### ISSUE TITLE
[BUG] Expedite светится красным, если превышен лимит в других дорожках

### ISSUE THREAD

**Issue by dmkuznetsov** [TinkoffCreditSystems/jira-helper#50]
**Describe the bug**
Expedite-дорожка светится красным, если превышен лимит в других дорожках

**To Reproduce**
1. Завести доску
2. Разместить на доске 2 дорожки (expedite и не-expedite)
3. Устанавливаем лимит на группу столбцов 
4. Перемещаем в эту группу столбцов кол-во карточек, превышающее лимит
5. Видим, что дорожка expedite так же покрасилась в красный

**Expected behavior**
Ожидается, что вертикальные лимиты на expedite-дорожку не распространяются

**Desktop (please complete the following information):**
 - JIRA 8

**Comment by pavelpower** [comment]
@dmkuznetsov а можете сделать скриншот настроек ваших swimlanes?

**Comment by dmkuznetsov** [comment]
Конечно: https://imgur.com/a/yb2ktZT
