### ISSUE TITLE
Нет возможности редактировать WIP limit на assignee

### ISSUE THREAD

**Issue by OxanaZa** [TinkoffCreditSystems/jira-helper#53]
1. Заведены WIPLimit на assignee(несколько Swimlanes и несколько колонок)
2. Нужно убрать/добавить еще одну колонку/Swimlanes

Для того, чтобы что-то изменить, например, появился еще один Swimlanes, то нужно удалить уже созданный WIPlimit, а потом добавить новый WIPlimit на Assignee с измененным набором swimlanes/columns. Если очень много таких правил, то очень утомительно делать такие изменения.

**Comment by pavelpower** [comment]
Похоже, что над сделать возможность сразу еще на несколько человек одинаковые правила применить
+ возможность отредактировать ограничения индивидуально

**Comment by pavelpower** [comment]
<img width="799" alt="Снимок экрана 2020-09-01 в 13 58 23" src="https://user-images.githubusercontent.com/301646/91841748-896ca800-ec5b-11ea-9634-0323fc5d19b7.png">
