### ISSUE TITLE
Feature: Настройки WIP limit на Assignee не копируются при копировании Kanban board

### ISSUE THREAD

**Issue by OxanaZa** [TinkoffCreditSystems/jira-helper#54]
При копировании Kanban board через меню Board/Copy. Настройки WIP limit на Assignee не копируются. Возможно, что не копируются вообще все WIPlimit, но у меня только один тип установлен,поэтому могу говорить только про один.

**Comment by pavelpower** [comment]
Ох, это конечно разные операции.
Операции с бордом это функция Atlassian, а настройки - это относиться к плагину.

Хотя, отдельной функцией возможно сделать копирование настроек jira-helper

**Comment by pavelpower** [comment]
Можно сделать такой алгоритм
1. Перехватить событие на "копиррование борда"
2. Запросить данные настроек текущего борда
3. Сохранить эти данные в local Storage
4. Передать обратно прерывание событию копированию борда
5. Отловить модификацию страницы после загрузки
6. Показать кнопку "применить сохраненные настройки"

**Comment by pavelpower** [comment]
Второй вариант
1. В контекстном меню нажать кнопку "скопировать настройки jira-helper"
2. Сохранить настройки на localStorege 
3. Открыть новый борд
4. Из контекстного меню нажать кнопку "применить настройки jira-helper"

**Comment by pavelpower** [comment]
Хотя контекстное меню не для этого.
Нужно вынести кнопку в настройки борда

**Comment by davakh** [comment]
Поисследовали, среди разных версий `jira` и разных возможностях копирования, трудно сделать чтобы работало так, как нам хотелось, и не привносило багов в работу самой `jira`. К сожалению, решили отказаться, из-за вызываемых багов в работе jira, при попытке расширить функционал копирования. 

В целом, если копирование доски не такая ежедневная задача, то можно перенести весь функционал руками довольно быстро.
