### ISSUE TITLE
Feature: 85 перцентиль на Control Chart

### ISSUE THREAD

**Issue by britishpop** [TinkoffCreditSystems/jira-helper#56]
**Is your feature request related to a problem? Please describe.**
На контрол чарте нельзя посмотреть что вылезает за 85%

**Describe the solution you'd like**
Хотелось бы иметь полоску, которая отсекала бы 85% всех задач в текущем фильтре

**Describe alternatives you've considered**
Использовал JFC, но там только сиюминутное распределение, а хочется смотреть по школе времени

**Comment by pavelpower** [comment]
Быстрое решение - посмотреть 85% там и поставить SLA-линию в Control Chart
Подсчет - дорогая операция, с точки зрения выгрузки данных. Для себя такое точно делать не будем...

Ну а вот сделать не одну линию SLA а несколько - кажется дравым

**Comment by britishpop** [comment]
Несколько SLA - это бы решило проблему, да. Вместе с JFC это бы решило проблему
