### ISSUE TITLE
[BUG] - не Мерджит колонки в общий вип лимит

### ISSUE THREAD

**Issue by djnixon** [TinkoffCreditSystems/jira-helper#68]
**Describe the bug**
В  настройках доски не могу объединить колонки в общий вип, после нажатия на merge ничего не происходит, после save - в консоли вылезает ошибка. Браузера на рабочем ноуте, управляется администратором сети. Все остальные фичи хелпера работают нормально.
Браузер Chrome 83.0.4103.61 64бит
версия jira 7.1.6

**To Reproduce**

1. зайти в настройки доски
2. нажать мердж
3. ничего не происходит
4. после save  в консоли ошибка

**Expected behavior**
ожидаю видеть как на уроке плашку в каджой колонке для выбора какие колонки объединять каким лимитом

Скриншоты
https://yadi.sk/i/qHADTjyhQp1iWg
https://yadi.sk/i/rxwzCl3ijJEhCg
https://yadi.sk/i/_dAM_lxiZSWhdQ
https://yadi.sk/i/-xnbPLdf6vOH8Q

**Desktop (please complete the following information):**
 - JIRA 7

**Comment by pavelpower** [comment]
Может вообще стоит пересмотреть способ выбора лимитов на столбцы и сделать аналогично тому как выбираются персональные WIP-лимиты?

**Comment by britishpop** [comment]
![Screenshot 2020-09-11 at 18 08 25](https://user-images.githubusercontent.com/37972827/92942057-cdc92680-f459-11ea-85e6-6acd69048b7a.png)
Консоль при попытке мерджа

**Comment by davakh** [comment]
Проблемы были при попадании пустой группы колонок в список. Можно проверить на старых версиях, при попытке сохранить группу без добавлений колонок.
