### ISSUE TITLE
Feature: добавление CI

### ISSUE THREAD

**Issue by Maksimall89** [TinkoffCreditSystems/jira-helper#69]
**Is your feature request related to a problem? Please describe.**
Отсутствует CI для проверки корректности сборок и PR

**Describe the solution you'd like**
Добавил CI на основе Travis

**Describe alternatives you've considered**
Можно использовать также Github Actions

**Additional context**

**Comment by pavelpower** [comment]
Интересно, а можно как-то настроить чтобы от добавления тега релиза этот релиз автоматом заливался на WebStore?

**Comment by Maksimall89** [comment]
Merged #73 into master.
