### ISSUE TITLE
Feature: Расчет персональных wip-лимитов для Эпиков в свимлайнах

### ISSUE THREAD

**Issue by YAnikeeva** [TinkoffCreditSystems/jira-helper#83]
**Is your feature request related to a problem? Please describe.**
Я настроила персональный лимиты, но обнаружила, что количество задач в работе не считается.
 Стали разбираться и поняли, что дело в том, что дорожки настроены по эпикам.
Когда я поменяла организацию дорожкек с эпиков на запросы, персональные лимиты заработали.  

**Describe the solution you'd like**
Хочу возможность отображения персональных лимитов при настроенной группировки дорожек по эпикам

**Describe alternatives you've considered**
Не знаю 

**Additional context**
![image](https://user-images.githubusercontent.com/72991066/96285828-5d24a500-0fd7-11eb-8c4e-ced4d7e982c2.png)

![image](https://user-images.githubusercontent.com/72991066/96285747-3e261300-0fd7-11eb-9925-0e96d3c0e491.png)

**Comment by pavelpower** [comment]
Да, это точно нужно
