### ISSUE TITLE
Feature: WIP-лимиты на комбинации свимлайнов и колонок

### ISSUE THREAD

**Issue by SBabanova** [TinkoffCreditSystems/jira-helper#88]
**Is your feature request related to a problem? Please describe.**
Для управления потоком при планировании задач есть потребность отдельно ограничить количество задач разных типов (определяется свимлайном) в одной колонке
Также есть потребность не учитывать некоторые колонки в CONWIP на свимлайн (например колонки TODO и DONE)
![image](https://user-images.githubusercontent.com/38456432/101354941-f751ec80-38a6-11eb-903d-ed8da23ae714.png)
![image](https://user-images.githubusercontent.com/38456432/101355404-924ac680-38a7-11eb-9242-e2bcbe16e821.png)

**Describe the solution you'd like**
Добавить поп-ап по аналогии с "Person limits"
В поп-апе можно выбрать набор колонок и свимлайнов и назначить им лимит
На доске рисовать лимит на свимлайны только на выбраных колонках
![image](https://user-images.githubusercontent.com/38456432/101355948-6845d400-38a8-11eb-96de-485dc111bc1e.png)

**Comment by pavelpower** [comment]
Решается ли эта задача при помощи https://github.com/TinkoffCreditSystems/jira-helper/issues/100
реализованой в версии 2.11.0?

**Comment by AndreyMoiseev** [comment]
@pavelpower а как это можно решить с помощью командных лимитов? И как эти командные лимиты настраиваются, я что-то не нашел.

Пока что решил у себя проблему так - добавил дополнительный фильтр на незавершенные задачи, в итоге у меня в столбце DONE на доске ничего не отображается, и, соответственно, в WIP-лимите на свимлейн не учитывается, но при этом в отчетах задачи в DONE отображаются правильно.
Столбец TO DO у меня используется как буфер между бэклогом и разработкой, поэтому в принципе распространение не него WIP-лимита не мешает. Но если бы было можно исключить из горизонтального WIP-лимита отдельные колонки - можно было бы отказаться от промежуточного буфера и отображать бэклог непосредственно на доске.

**Comment by pavelpower** [comment]
@AndreyMoiseev  у вас задачи в последнем столбце разве флаг в Resolution не проставляется?
